In [1]:
! pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in d:\new softwares\anaconda3\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in d:\new softwares\anaconda3\lib\site-packages (from lightgbm) (1.13.1)
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --- ------------------------------------ 0.1/1.5 MB 3.6 MB/s eta 0:00:01
   ------ --------------------------------- 0.2/1.5 MB 2.5 MB/s eta 0:00:01
   --------- ------------------------------ 0.3/1.5 MB 2.9 MB/s eta 0:00:01
   ----------- ---------------------------- 0.4/1.5 MB 2.6 MB/s eta 0:00:01
   ------------- -------------------------- 0.5/1.5 MB 2.4 MB/s eta 0:00:01
   ---------------- ----------------------- 0.6/1.5 MB 2.3 MB/s eta 0:00:01
   ------------------- -------------------- 0.7/1.5 MB 2.4 MB/s eta 0:00:01
   --------------------- ------------------ 0.8/1.5 MB 2.4 MB/s eta 0:00:01
   ------------------------- -------------- 0.9/1.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------- ----------- 1.0/1.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------- -------- 1.2/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 1.3/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  1.4/1.5 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 1.6 MB/s eta 0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.6.0

In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [10]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]

In [12]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [15]:
from lightgbm import LGBMRegressor

In [16]:
regressor=LGBMRegressor()

In [17]:
regressor.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000080 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 313
[LightGBM] [Info] Number of data points in the train set: 936, number of used features: 5
[LightGBM] [Info] Start training from score 13232.916456

LGBMRegressor()

In [18]:
y_pred=regressor.predict(x_test)

In [19]:
from sklearn.metrics import r2_score

In [20]:
r_score=r2_score(y_test,y_pred)

In [21]:
r_score

0.86603193419773

In [22]:
import pickle

In [23]:
filename="finalizer_model.sav"

In [24]:
pickle.dump(regressor,open(filename,'wb'))

In [26]:
loaded_model=pickle.load(open("finalizer_model.sav",'rb'))

In [27]:
result=loaded_model.predict([[1234,345,4565,1,0]])

In [28]:
result

array([16856.07254035])